config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  resources :users, except: [:new]
  resources :articles
  get 'signup', to: 'users#new'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources  :categories, except: [:destroy]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :article_categories
  has_many :categories, through: :article_categories

  validates :titre, presence: true, length: { minimum: 6, maximum: 100 }
  validates :description, presence: true, length: { minimum: 10, maximum: 200 }

end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
  belongs_to :article
  belongs_to :category

end

app/models/category.rb
class Category < ApplicationRecord
  has_many :article_categories
  has_many :articles, through: :article_categories

  validates :name, presence: true, length: { minimum: 3, maximum: 25 }
  validates_uniqueness_of :name

end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.usermail = usermail.downcase }
  has_many :articles, dependent: :destroy

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :username, presence: true, uniqueness: { case_sensitive: false }, length: { minimum: 3, maximum: 40 }
  validates :usermail, uniqueness: { case_sensitive: false }, length: { maximum: 40 }, format: { with: VALID_EMAIL_REGEX }

  has_secure_password

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :current_user, :logged_in?
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:alert] = "Vous devez être loggé pour voir les actions"
      redirect_to login_path
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[ show edit update destroy ]
  before_action :require_user, except: %i[show index]
  before_action :require_same_user, only: %i[edit update destroy]

  # GET /articles or /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1 or /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles or /articles.json
  def create
    @article = Article.new(article_params)
    @article.user = current_user

    respond_to do |format|
      if @article.save
        flash[:notice] = "L'article a été enregistré"
        format.html { redirect_to article_url(@article) }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1 or /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to article_url(@article), notice: "L'article est modifié." }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1 or /articles/1.json
  def destroy
    @article.destroy

    respond_to do |format|
      format.html { redirect_to articles_url, notice: "L'article est supprimé." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_article
    @article = Article.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def article_params
    params.require(:article).permit(:titre, :description, category_ids: [])
  end

  def require_same_user
    if current_user != @article.user && !current_user.admin?
      flash[:alert] = 'Vous pouvez éditer ou supprimer votre article'
      redirect_to @article
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  before_action :require_admin, except: [:index, :show]

  def new
    @category = Category.new
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      flash[:notice] = "La catégorie est mise à jour"
      redirect_to @category
    else
      render 'edit'
    end
  end

  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
    @articles = @category.articles.paginate(page: params[:page], per_page: 5)
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = "La catégorie est bien enregistrée"
      redirect_to @category
    else
      render 'new'
    end
  end

  private
  def category_params
    params.require(:category).permit(:name)
  end

  def require_admin
    if !(logged_in? && current_user.admin?)
      flash[:alert] = "Seulement l'admin peut faire cette action"
      redirect_to categories_path
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    redirect_to articles_path if logged_in?
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new

  end

  def create
    user = User.find_by(usermail: params[:session][:usermail].downcase)
    if user
      # && user.authenticate(params[:session][:password_digest])
      session[:user_id] = user.id
      flash[:notice] = "Login succès sur Alpha blog"
      redirect_to user
    else
      flash.now[:alerte]="Mauvais utilisateur"
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "Log out"
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]
  before_action :require_user, except: %i[edit update]
  before_action :require_same_user, except: %i[edit update destroy]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
    @articles = @user.articles.paginate(page: params[:page], per_page: 5)
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        session[:user_id] = @user.id
        format.html { redirect_to articles_path, notice: "Bienvenue sur Alpha blog." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to articles_path, notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :signup, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy
    session[:user_id] = nil if @user == current_user
    flash[:alert] = "Le compte et les articles associés seront supprimés"
    redirect_to articles_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:username, :usermail, :password_digest)
    end

  def require_same_user 
    if current_user != @user && !current_user.admin?
      flash[:alert] = 'Vous pouvez éditer ou supprimer votre propre profil'
      redirect_to @user
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def gravatar_for(user, options = { size: 80 })
    email_adress = user.usermail.downcase
    hash = Digest::MD5.hexdigest(email_adress)
    size = options[:size]
    gravatar_url = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
    image_tag(gravatar_url, alt: user.username, class: "rounded shadow mx-auto d-block")
  end

end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_article.html.erb
<table>
  <thead>
  <tr>
    <th>Titre</th>
    <th>Description</th>
    <th>Categories</th>
    <th colspan="3">Actions</th>
  </tr>
  </thead>

  <tbody>
  <% @articles.each do |article| %>
    <tr>
      <td><%= article.titre %></td>
      <td><%= article.description %></td>
      <td><% if article.categories.any? %>
        <div class="mt-2">
          <%= render article.categories %>
        </div>
        <% end %></td>
      <td><%= link_to 'Voir', article %></td>
      <% if logged_in?  && (article.user == current_user || current_user.admin?) %>
        <td><%= link_to 'Modifier', edit_article_path(article) %></td>
        <td><%= link_to 'Supprimer', article, method: :delete, data: { confirm: 'Etes vous sûr?' } %></td>7
      <% end %>

    </tr>
  <% end %>
  </tbody>
</table>

app/views/articles/_form.html.erb
<%= form_with(model: @article) do |form| %>
  <%=render 'error/errors', obj: @article %>

  <div class="field">
    <%= form.label :titre %>
    <%= form.text_field :titre %>
  </div>

  <div class="field">
    <%= form.label :category %>
    <%= form.text_area :category %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.collection_select(:category_ids, Category.all, :id, :name, { :prompt => "Sélectionner une catégorie" }, { multiple: true,
        size: 3, class: "custom-select shadow rounded" }) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Détail', @article %> |
<%= link_to 'Retour', articles_path %>

app/views/articles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Liste des articles</h1>

<%= render 'articles/article' %>

<br>

<%= link_to 'Nouvel Article', new_article_path %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Retour', articles_path %>

app/views/articles/show.html.erb
<h1>Show de l'article</h1>

<div>by <%= @article.user.username %> </div>
<% if @article.categories.any? %>
  <div class="mt-2">
    <%= render @article.categories %>
  </div>
<% end %>
  <strong>Titre:</strong>
  <%= @article.titre %>
</p>

<p>
  <strong>Description:</strong>
  <%= @article.description %>
</p>

<% if logged_in? && (@article.user == current_user || current_user.admin?) %>
  <%= link_to 'Modifier', edit_article_path(@article) %>
  <%= link_to 'Supprimer', article_path(@article), method: :delete, date: {confimr: "Etes-vous sûr?"} %>
<% end %>
<%= link_to 'Retour', articles_path %>

app/views/categories/_category.html.erb
<%= link_to category.name, category_path(category), class: "badge badge-pill badge-info mr-1" %>

app/views/categories/_form.html.erb
<%= form_with(model: @category) do |form| %>

    <%= render 'error/errors', obj: @category %>
  
    <div class="field">
      <%= form.label :Nom, "Nom de la catégorie" %>
      <%= form.text_field :name %>
    </div>
  
    <div class="actions">
      <%= form.submit("Créer") %>
    </div>
  <% end %>

app/views/categories/edit.html.erb
<h1>Mise à jour de la catégorie</h1>

<%= render 'form' %>

app/views/categories/index.html.erb
<h1>Liste des catégories</h1>

<table>
  <thead>
    <tr>
      <th>Titre</th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |categorie| %>
      <tr>
        <td><%= categorie.name %>
        <p class="card-text"><%= pluralize(categorie.articles.count, "article") %></p></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/categories/new.html.erb
<h1>Nouvelle catégorie</h1>

<%= render 'form' %>

app/views/categories/show.html.erb
<h1>Liste catégorie <%= @category.name %></h1>

<%= render 'articles/article' %>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <%= msg %>
<% end %>

app/views/layouts/_navigation.html.erb
<div>
  <% if logged_in? %>
    <%= link_to current_user.username, user_path(current_user)%>
    <li>
      <%= link_to 'Log Out', logout_path, method: :delete %>
    </li>
  <% else %>
    <% link_to 'Log In', login_path %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlogCba</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'layouts/messages' %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h2>Bienvenue sur l'alpha blog</h2>
<br>

<%= link_to "Sign Up", signup_path %>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>

<%=render 'error/errors', obj: @user %>

  <div class="field">
    <%= form.label :Nom %>
    <%= form.text_field :username %>
  </div>

  <div class="field">
    <%= form.label :mail %>
    <%= form.text_field :usermail %>
  </div>

  <div class="field">
    <%= form.label :password_digest %>
    <%= form.text_field :password_digest %>
  </div>

  <div class="actions">
    <%= form.submit(@user.new_record? ?  "Sign Up" : "Modifier votre profil") %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Modifier votre profil</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Utilisateurs</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Usermail</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.username, user %></td>
        <td><%= user.usermail %></td>
        <td><%= link_to 'View profil', user %></td>
        <% if logged_in? %>
          <% if user == current_user %>
            <td><%= link_to 'Edit profil', edit_user_path(user) %></td>
          <% end %>
          <%if current_user.admin? %>
            <td><%= link_to "Supprimer le profil", user_path(user), method: :delete, data: {confirm: "Etes vous sûr de vouloir supprimer le compte?"} %></td>
          <% end %>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/users/new.html.erb
<h1>Authentification de Alpha blog</h1>

<%= render 'form', user: @user %>

<%= link_to 'retour', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>
<h1>Votre profil</h1>
<p>
  <%= gravatar_for @user, size: 200 %>
  <h3 class="text-center mt-4">Articles</h3>
  <%= render 'articles/article' %>

  <br>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>Usemail:</strong>
  <%= @user.usermail %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>